# Generated by Django 2.0 on 2018-09-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='账号')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮箱')),
                ('nickname', models.CharField(max_length=16, verbose_name='昵称')),
                ('hp', models.PositiveIntegerField(default=0, verbose_name='生命值')),
                ('atk', models.PositiveIntegerField(default=0, verbose_name='攻击力')),
                ('defense', models.PositiveIntegerField(default=0, verbose_name='防御力')),
                ('coin', models.PositiveIntegerField(default=0, verbose_name='金币')),
            ],
        ),
    ]
