# Generated by Django 2.0 on 2018-09-19 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20180912_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default="{'level':0,'bottom':None,'top':None}", verbose_name='地图数据')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='建造者')),
            ],
            options={
                'verbose_name': '塔',
                'verbose_name_plural': '塔',
            },
        ),
        migrations.CreateModel(
            name='TowerPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.PositiveIntegerField(default=0, verbose_name='生命值加成')),
                ('atk', models.PositiveIntegerField(default=0, verbose_name='攻击力加成')),
                ('defense', models.PositiveIntegerField(default=0, verbose_name='防御力加成')),
                ('x', models.PositiveSmallIntegerField(default=0, verbose_name='横坐标')),
                ('y', models.PositiveSmallIntegerField(default=0, verbose_name='纵坐标')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='当前层数')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='玩家')),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Tower', verbose_name='塔')),
            ],
            options={
                'verbose_name': '玩家属性',
                'verbose_name_plural': '玩家属性',
            },
        ),
    ]
